title: Default Page

tabs:
    content:
        label: Περιεχόμενο
        icon: text
        columns:
          - width: 2/3
            sections:
                content:
                    type: fields
                    fields:
                        introtext:
                            label: Εισαγωγικό κείμενο
                            type: textarea
                            buttons: false
                        blocks: fields/blocks

          - width: 1/3
            sections:
                pages:
                    type: pages
                    headline: Υποσελίδες
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
