title: Site

tabs:
    content:
        label: Σελίδες
        icon: page
        columns:
          - width: 2/3
            sections:
                hotels:
                    type: pages
                    headline: Ξενώνες
                    template: hotel
                    status: all
                    max: 2
                pages:
                    type: pages
                    headline: Σελίδες Περιεχομένου
                    template: default
                    status: all

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
