title: Site

tabs:
    content:
        label: Σελίδες
        icon: page
        columns:
          - width: 2/3
            sections:
                hotels:
                    type: pages
                    headline: Ξενώνες
                    template: hotel
                    status: all
                    max: 2
                pages:
                    type: pages
                    headline: Σελίδες Περιεχομένου
                    template: default
                    status: all
                gallery:
                    type: pages
                    headline: Εικόνες
                    template: gallery
                    status: all
                    max: 1
                contact:
                    type: pages
                    headline: Επικοινωνία
                    template: contact
                    status: all
                    max: 1

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
                periods:
                    type: fields
                    fields:
                        lowseason:
                            type: textarea
                            buttons: false
                            label: Χαμηλή Περίοδος
                        midseason:
                            type: textarea
                            buttons: false
                            label: Μεσαία Περίοδος
                        highseason:
                            type: textarea
                            buttons: false
                            label: Υψηλή Περίοδος
    seo: tabs/seo
