title: Site

tabs:
    content:
        label: Σελίδες
        icon: page
        columns:
          - width: 2/3
            sections:
                hotels:
                    type: pages
                    headline: Ξενώνες
                    template: hotel
                    status: all
                    max: 2
                pages:
                    type: pages
                    headline: Σελίδες Περιεχομένου
                    template: default
                    status: all
                gallery:
                    type: pages
                    headline: Εικόνες
                    template: gallery
                    status: all
                    max: 1
                contact:
                    type: pages
                    headline: Επικοινωνία
                    template: contact
                    status: all
                    max: 1
                legal:
                    type: pages
                    headline: Ψιλά γράμματα
                    template: simple
                    status: all

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    sitedata:
        label: Στοιχεία site
        icon: edit
        columns:
          - width: 2/3
            sections:
                datasite:
                    type: fields
                    fields:
                        titles:
                            label: Τίτλοι και περιγραφές
                            type: headline
                            numbered: false
                        sitesubtitle:
                            type: textarea
                            label: Υπότιτλος
                            buttons:
                              - bold
                              - italic
                        logos:
                            label: Λογότυπα
                            type: headline
                            numbered: false
                        ghermanikosmall:
                            label: Γερμανικό μικρό
                            type: files
                            multiple: false
                        victoriasmall:
                            label: Βικτώρια μικρό
                            type: files
                            multiple: false
                        ghermaniko:
                            label: Γερμανικό
                            type: files
                            multiple: false
                        victoria:
                            label: Βικτώρια
                            type: files
                            multiple: false
                        seasons:
                            label: Περίοδοι
                            type: headline
                            numbered: false
                        lowseason:
                            type: textarea
                            buttons: false
                            label: Χαμηλή Περίοδος
                        midseason:
                            type: textarea
                            buttons: false
                            label: Μεσαία Περίοδος
                        highseason:
                            type: textarea
                            buttons: false
                            label: Υψηλή Περίοδος
                        phones:
                            label: Τηλέφωνα
                            type: headline
                            numbered: false
                        fixed:
                            type: text
                            label: Σταθερό
                        mobile:
                            type: text
                            label: Κινητό
                        mails:
                            label: Email
                            type: headline
                            numbered: false
                        maillist:
                            type: structure
                            label: Λίστα email
                            fields:
                                 email:
                                    label: Email
                                    type: email
                        social:
                            label: Social Media
                            type: headline
                            numbered: false
                        facebook:
                            label: Facebook
                            type: url
                        twitter:
                            label: Twitter
                            type: url
                        instagram:
                            label: Instagram
                            type: url
                        footer:
                            label: Κείμενα Footer
                            type: headline
                            numbered: false
                        footertitle:
                            type: textarea
                            buttons:
                              - bold
                              - italic
                            label: Τίτλος Footer
                        footerlocation:
                            type: textarea
                            buttons:
                              - bold
                              - italic
                            label: Τοποθεσία Footer

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles

    seo: tabs/seo
